### ISSUE TITLE
Can't install

### ISSUE THREAD

**Issue by alyeen** [asherbernardi/jsgfplugin#1]
I wanted to check out this plugin, but I cannot find it in IntelliJ IDEA marketplace. Settings/Plugins/Install Plugin from Disk also doesn't work.

**Comment by asherbernardi** [comment]
Hi Alyeen! Do you have the latest version of Intellij IDEA? Since this is a new plugin, you may have to update your IDE. You need a version of at least 2019.3.3
If that still doesn't work, let me know.
