### ISSUE TITLE
Doesn't work with the latest update of my IDE(intellij).

### ISSUE THREAD

**Issue by OnkarGarg** [asherbernardi/jsgfplugin#2]
I really liked your plugin as I have used it before, but after I updated my IDE, your plugin could not function and shows this:

"Incompatible: requires IDE build 211.* or older"

Please fix this issue as your plugin is most efficient and easy to use, at least according to me.
I hope you fix it soon.

**Comment by asherbernardi** [comment]
Hello! I'm sorry for the inconvenience. I have been working on updating the plugin, but it takes a few days. It should be updated for the newest version of IntelliJ soon.

**Comment by OnkarGarg** [comment]
Thanks for the fast reply.
Great to know that, thanks again👍👍👍👍.

**Comment by OnkarGarg** [comment]
Hey,
just wanted to ask you if you could send me a message when the plugin is updated.

thanks in advance!

**Comment by asherbernardi** [comment]
Updated

**Comment by OnkarGarg** [comment]
Thanks!
